GET http://localhost:3001/api/v1/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsIGd1YSIsImlkIjoiNWZhYzVjYjllYzVkNzgzMjNjYjQwMDkwIiwiaWF0IjoxNjA1MTMxODU3fQ.1IRXvn_L65BdEQPqY-soJlC7eYliOZYOL-Cw_sUDbNU
############

POST http://localhost:3001/api/v1/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsIGd1YSIsImlkIjoiNWZhYzVjYjllYzVkNzgzMjNjYjQwMDkwIiwiaWF0IjoxNjA1MTMxODU3fQ.1IRXvn_L65BdEQPqY-soJlC7eYliOZYOL-Cw_sUDbNU
Content-Type: application/json

{
    "title": "test post",
	"author": "el billy janir",
	"url": "https://billDestiny.com/mind-blogs/",
	"likes" : 15
	}
############

GET http://localhost:3001/api/v1/blog/5fa36089b9984147019f986b HTTP/1.1

############


DELETE http://localhost:3001/api/v1/blog/5faa08bc929442cc99b549a7 HTTP/1.1


############

PUT http://localhost:3001/api/v1/blog/5fa36bbabe83b75c80402a40 HTTP/1.1

############

GET http://localhost:3001/api/v1/user HTTP/1.1


############

DELETE  http://localhost:3001/api/v1/user/5faa076668aa2cca8f97dc21 HTTP/1.1


############

POST http://localhost:3001/api/v1/user HTTP/1.1
Content-Type: application/json

{
    "username": "el sesh",
    "name": "ayy",
    "password" : "22ss"
}


##########


POST http://localhost:3001/api/v1/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsIGd1YSIsImlkIjoiNWZhYzVjYjllYzVkNzgzMjNjYjQwMDkwIiwiaWF0IjoxNjA1MTMxODU3fQ.1IRXvn_L65BdEQPqY-soJlC7eYliOZYOL-Cw_sUDbNU
Content-Type: application/json

{
    "username": "el gua",
    "password" : "22ss"
}



